# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runpod < Formula
  desc ""
  homepage "https://github.com/rachfop/runpod"
  version "0.8"

  on_macos do
    url "https://github.com/rachfop/runpodctl/releases/download/v0.8/runpodctl_0.8_darwin_all.tar.gz"
    sha256 "e32e8defe759f5cdef977e493ee3c4c6f3ae53cacd62a3bd90adeb1908c6a91a"

    def install
      bin.install "runpodctl"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rachfop/runpodctl/releases/download/v0.8/runpodctl_0.8_linux_arm64.tar.gz"
      sha256 "963e2e5df4e8910845c7b010826c1a86a420720d3eb24d70bd82cfe0f3a98f08"

      def install
        bin.install "runpod"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rachfop/runpodctl/releases/download/v0.8/runpodctl_0.8_linux_amd64.tar.gz"
      sha256 "6bfd818fb75bf642c3abce577d28c132cba51e3e614ab4b549e603903a3d7e0b"

      def install
        bin.install "runpod"
      end
    end
  end
end
