# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runpodctl < Formula
  desc ""
  homepage "https://github.com/rachfop/runpodctl"
  version "0.01"

  on_macos do
    url "https://github.com/rachfop/runpodctl/releases/download/v0.01/runpodctl_0.01_darwin_all.tar.gz"
    sha256 "f1c59a18a9ceaf78d4dc82c952461b51ebd2289ac31d2559ee98ba4e2d308a39"

    def install
      bin.install "runpodctl"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rachfop/runpodctl/releases/download/v0.01/runpodctl_0.01_linux_arm64.tar.gz"
      sha256 "95b24514183bfe273218ae6f26b94d875ecf50de6b3db38d4fbf81e7377ebc73"

      def install
        bin.install "runpodctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rachfop/runpodctl/releases/download/v0.01/runpodctl_0.01_linux_amd64.tar.gz"
      sha256 "91c1bfc36cb350b3deb0fc3c130bc611079f0d5645880220ccc90b305d2f0a44"

      def install
        bin.install "runpodctl"
      end
    end
  end
end
